apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: react-app-template
  title: React Application Template
  description: Scaffolds a new React application using create-react-app.
  tags:
    - react
    - frontend
    - template
spec:
  owner: team/frontend
  type: website
  parameters:
    - title: Project Information
      properties:
        name:
          title: Application Name
          description: The name of your React application.
          type: string
        description:
          title: Application Description
          description: A brief description of your React application.
          type: string
          default: A new React application
  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: https://github.com/facebook/create-react-app/archive/refs/heads/main.zip
        targetPath: .
        values:
          name: '{{ parameters.name }}'
    - id: setup
      name: Initialize Project
      action: execute:shell
      input:
        shell: bash
        script: |
          mv create-react-app-main/* .
          mv create-react-app-main/.* .
          rm -rf create-react-app-main
          npm install
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com/your-org/{{ parameters.name }}
        description: '{{ parameters.description }}'
        defaultBranch: main
        sourcePath: .
  output:
    links:
      - title: Repository
        url: '{{ steps.publish.output.remoteUrl }}'
