apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-react-app
  title: Create React App
  description: Template to bootstrap a React app using Create React App
  tags:
    - react
    - javascript
    - frontend
spec:
  owner: frontend-team
  type: website
  parameters:
    - title: Project Details
      properties:
        name:
          title: Project Name
          description: Name of the React application
          type: string
        useTypescript:
          title: Use TypeScript
          description: Whether to initialize the project with TypeScript
          type: boolean
          default: false
  steps:
    - id: create-react-app
      name: Create React App
      action: shell:execute
      input:
        command: npx
        args:
          - create-react-app
          - "{{ parameters.name }}"
          - "{{ parameters.useTypescript | ternary('--template typescript', '') }}"
    - id: add-to-repo
      name: Prepare Repository
      action: publish:github
      input:
        repoUrl: "github.com/org-name/{{ parameters.name }}"
        defaultBranch: main
        sourcePath: "{{ parameters.name }}"
  output:
    links:
      - title: Repository
        url: "{{ steps.add-to-repo.output.remoteUrl }}"
      - title: Deployed App
        url: "https://your-deployment-url.com/{{ parameters.name }}"
